name: ubuntu
  
on:
  pull_request:
  push:
    branches:
    - master

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      PG: ${{ matrix.postgres-version }}
    strategy:
      fail-fast: false
      matrix:
        postgres-version:
          - '14'
          - '15'
          - '16'
          - '17'
          - '18'

    steps:
    - uses: actions/checkout@v5
    - name: Set up packages
      run: |
        set -e
        sudo apt-get update -y
        sudo apt-get install -y curl ca-certificates gnupg liblz4-dev libkrb5-dev libipc-run-perl
        sudo sh -c "echo \"deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main $PG\" > /etc/apt/sources.list.d/pgdg.list"
        sudo sh -c "curl -s -o - https://www.postgresql.org/media/keys/ACCC4CF8.asc | gpg --dearmor > /etc/apt/trusted.gpg.d/apt.postgresql.org.gpg"
        sudo apt-get update -y
        sudo apt-get install -y --no-install-suggests --no-install-recommends postgresql-common
        # forbid creation of a main cluster when package is installed
        sudo sed -ri 's/#(create_main_cluster) .*$/\1 = false/' /etc/postgresql-common/createcluster.conf
        sudo apt-get install -y --no-install-suggests --no-install-recommends postgresql-$PG postgresql-server-dev-$PG

    - name: Compile and install pg_streampack
      run: |
        set -e
        make PG_CONFIG=/usr/lib/postgresql/$PG/bin/pg_config USE_PGXS=1 enable_coverage=yes
        sudo make PG_CONFIG=/usr/lib/postgresql/$PG/bin/pg_config USE_PGXS=1 install
        make PG_CONFIG=/usr/lib/postgresql/$PG/bin/pg_config USE_PGXS=1 enable_coverage=yes with_llvm=no clean all
        sudo make PG_CONFIG=/usr/lib/postgresql/$PG/bin/pg_config USE_PGXS=1 with_llvm=no install

    - name: Run tests
      run: |
        make PG_CONFIG=/usr/lib/postgresql/$PG/bin/pg_config USE_PGXS=1 installcheck || (cat regression.diffs && false)

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: ${{ matrix.postgres-version }}
